# Generated by Django 6.0 on 2026-04-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0002_remove_activity_user_activity_owner_company_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartcrm.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='smartcrm.lead'),
        ),
    ]
