# Generated by Django 6.0 on 2026-04-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0003_task_contact_alter_deal_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
