# Generated by Django 6.0 on 2026-04-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0004_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='owner',
        ),
    ]
