# Generated by Django 6.0 on 2026-05-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0006_remove_task_contact_remove_lead_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='smartcrm.company'),
        ),
    ]
