# Generated by Django 6.0 on 2026-05-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0009_alter_activity_created_at_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
