# Generated by Django 6.0 on 2026-05-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0011_alter_activity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
