# Generated by Django 6.0 on 2026-05-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0012_lead_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_deleted',
        ),
    ]
