# Generated by Django 6.0 on 2026-05-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0013_remove_lead_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='smartcrm.lead'),
        ),
    ]
