# Generated by Django 6.0 on 2026-05-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0014_alter_deal_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='smartcrm.deal'),
        ),
    ]
