# Generated by Django 6.0 on 2026-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcrm', '0015_task_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('qualification', 'Qualification'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('review', 'Contract Review')], default='qualification', max_length=50),
        ),
    ]
